
PAD_VALUE = -1
JOINT_LABEL_SEP = '/'


# Optimizer hyperparameters
DEFAULT_LEARNING_RATE = 0.04
DEFAULT_DECAY_RATE = 1.5
DEFAULT_DECAY_STEPS = 5000
DEFAULT_WARMUP_STEPS = 8000
DEFAULT_MU = 0.9
DEFAULT_NU = 0.98
DEFAULT_GAMMA = 0
DEFAULT_EPSILON = 1e-12
DEFAULT_CHI = 0